/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as SariRouteImport } from './routes/sari'
import { Route as IndexRouteImport } from './routes/index'
import { Route as KategoriSlugRouteImport } from './routes/kategori.$slug'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SariRoute = SariRouteImport.update({
  id: '/sari',
  path: '/sari',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const KategoriSlugRoute = KategoriSlugRouteImport.update({
  id: '/kategori/$slug',
  path: '/kategori/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sari': typeof SariRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/kategori/$slug': typeof KategoriSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sari': typeof SariRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/kategori/$slug': typeof KategoriSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sari': typeof SariRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/kategori/$slug': typeof KategoriSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sari' | '/sitemap.xml' | '/kategori/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sari' | '/sitemap.xml' | '/kategori/$slug'
  id: '__root__' | '/' | '/sari' | '/sitemap.xml' | '/kategori/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SariRoute: typeof SariRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  KategoriSlugRoute: typeof KategoriSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sari': {
      id: '/sari'
      path: '/sari'
      fullPath: '/sari'
      preLoaderRoute: typeof SariRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kategori/$slug': {
      id: '/kategori/$slug'
      path: '/kategori/$slug'
      fullPath: '/kategori/$slug'
      preLoaderRoute: typeof KategoriSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SariRoute: SariRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  KategoriSlugRoute: KategoriSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
